/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.network.admin.view;

import java.awt.CardLayout;
import javax.swing.JPanel;
import org.biogen.ecosystem.admin.view.AnalyticsDashboard;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.network.model.OperationalRegion;
import org.biogen.user.model.BusinessUser;

/**
 *
 * @author deveshkandpal
 */
public class NetworkAdminWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form NetworkAdminWorkPanel
     */
    private Ecosystem system;
    private JPanel container;
    private BusinessUser user;
    private OperationalRegion network;

    public NetworkAdminWorkPanel(Ecosystem system, JPanel container, BusinessUser user) {
        initComponents();
        this.system = system;
        this.container = container;
        this.user = user;
        this.network = this.system.getOpRegionDirectory()
                .getOperationalRegionList()
                .stream()
                .filter(f -> f.getRegionId() == user.getNetworkId())
                .findFirst()
                .get();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        generateReports = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Network Admin Work Area");

        generateReports.setText("Cross Enterprise Analytics");
        generateReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(generateReports))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(generateReports)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportsActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        NetworkAnalyticsDashboard panel = new NetworkAnalyticsDashboard(network, system);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("NetworkAnalyticsDashboard", panel);
        layout.next(container);

    }//GEN-LAST:event_generateReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateReports;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
