/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.enterprise.admin.chem.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JPanel;
import org.biogen.business.chem.model.Compound;
import org.biogen.business.common.Status;
import org.biogen.organization.admin.chem.view.ManageNewCompoundRequestPanel;
import org.biogen.organization.work.model.WorkRequest;
import org.biogen.organization.work.model.WorkRequestStatus;
import org.biogen.work.attachment.model.NewCompoundApprovalAttachment;

/**
 *
 * @author deveshkandpal
 */
public class ApproveOrDeclineNewCompoundWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form ApproveOrDeclineWorkRequest
     */
    private JPanel container;
    private WorkRequest workRequest;

    public ApproveOrDeclineNewCompoundWorkRequest(JPanel container, WorkRequest workRequest) {
        initComponents();
        this.workRequest = workRequest;
        this.container = container;
        populateForm();
    }

    public void populateForm() {
        Compound c = ((NewCompoundApprovalAttachment) workRequest.getAttachment()).getCompound();
        requestTypeField.setText(workRequest.getAttachment().getAttachmentType().toString());
        formulaField.setText(c.getFormula());
        commentsField.setText(workRequest.getComments());
        compoundNameField.setText(c.getName());
        descriptionField.setText(c.getDescription());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        formulaField = new javax.swing.JTextField();
        compoundNameField = new javax.swing.JTextField();
        requestTypeField = new javax.swing.JTextField();
        descriptionField = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsField = new javax.swing.JTextArea();
        updateRequestBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Manage New Compound Request");

        jLabel2.setText("Request Type");

        jLabel3.setText("Comments");

        jLabel4.setText("Compound Name");

        jLabel5.setText("Description");

        jLabel6.setText("Formula");

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Status");

        formulaField.setEditable(false);
        formulaField.setEnabled(false);

        compoundNameField.setEditable(false);
        compoundNameField.setEnabled(false);

        requestTypeField.setEditable(false);
        requestTypeField.setEnabled(false);

        descriptionField.setEditable(false);
        descriptionField.setEnabled(false);

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APPROVE", "DECLINE" }));

        commentsField.setEditable(false);
        commentsField.setColumns(20);
        commentsField.setRows(5);
        commentsField.setEnabled(false);
        jScrollPane1.setViewportView(commentsField);

        updateRequestBtn.setText("update request");
        updateRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRequestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(formulaField)
                                .addComponent(jLabel1)
                                .addComponent(requestTypeField)
                                .addComponent(compoundNameField)
                                .addComponent(descriptionField))
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 247, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateRequestBtn)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(formulaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(compoundNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(updateRequestBtn)
                .addGap(48, 48, 48)
                .addComponent(backBtn)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRequestBtnActionPerformed
        // TODO add your handling code here:

        this.workRequest.setEndDate(new Date());
        NewCompoundApprovalAttachment attachment = (NewCompoundApprovalAttachment) this.workRequest.getAttachment();

        if (statusComboBox.getSelectedItem().equals("APPROVE")) {
            this.workRequest.setStatus(WorkRequestStatus.APPROVED);
            this.workRequest.setComments("Request Approved");
            attachment.getCompound().setStatus(Status.APPROVED);

        } else {
            this.workRequest.setStatus(WorkRequestStatus.DENIED);
            this.workRequest.setComments("Request Rejected");
            attachment.getCompound().setStatus(Status.REJECTED);
        }

        redirectUser();
    }//GEN-LAST:event_updateRequestBtnActionPerformed

    public void redirectUser() {
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageWorkRequestPanel previousPanel = (ManageWorkRequestPanel) component;
        previousPanel.populateNewOrUpdatedWorkRequestTable();
        previousPanel.populateOtherWorkRequestTable();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }


    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        redirectUser();
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea commentsField;
    private javax.swing.JTextField compoundNameField;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JTextField formulaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField requestTypeField;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JButton updateRequestBtn;
    // End of variables declaration//GEN-END:variables
}
