/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.organization.admin.medicare.view;

import java.awt.CardLayout;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.biogen.business.enterprise.model.MedicareBusiness;
import org.biogen.business.medicare.model.ClinicalState;
import org.biogen.business.medicare.model.ClinicalStudy;
import org.biogen.ecosystem.admin.view.EditClinicalStudyPanel;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.network.model.OperationalRegion;
import org.biogen.organization.model.Hospital;
import org.biogen.organization.work.model.WorkRequest;
import org.biogen.organization.work.model.WorkRequestStatus;
import org.biogen.user.model.BusinessUser;
import org.biogen.work.attachment.model.AttachmentType;
import org.biogen.work.attachment.model.ClinicalStudyAttachment;

/**
 *
 * @author deveshkandpal
 */
public class ManageClinicalStudyPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageClinicalStudyPanel
     */
    private Ecosystem system;
    private JPanel container;
    private BusinessUser user;
    private MedicareBusiness enterprise;
    private OperationalRegion network;
    private Hospital organization;

    public ManageClinicalStudyPanel(
            Ecosystem system,
            JPanel container,
            BusinessUser user,
            MedicareBusiness enterprise,
            OperationalRegion network,
            Hospital organization
    ) {
        initComponents();
        this.system = system;
        this.container = container;
        this.user = user;
        this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;

    }

    public void populatePendingTrials() {
        DefaultTableModel model = (DefaultTableModel) pendingClinicalTrials.getModel();

        model.setRowCount(0);
        this.user.getWorkQueue()
                .getWorkRequestList()
                .stream()
                .filter(wr -> wr.getAttachment().getAttachmentType()
                == AttachmentType.ClinicalStudyAttachment && wr.getReceiver() == user
                && wr.getStatus() == WorkRequestStatus.NEW)
                .collect(Collectors.toList())
                .forEach(a -> {
                    ClinicalStudyAttachment attachment
                            = (ClinicalStudyAttachment) a.getAttachment();
                    if (attachment.getClinicalStudy().getState() == ClinicalState.PHASE1_STARTED) {

                        Object[] row = new Object[4];
                        row[0] = a;
                        row[1] = attachment.getClinicalStudy().getDrug().getDisease();
                        row[2] = attachment.getClinicalStudy().getDrug();
                        row[3] = attachment.getClinicalStudy().getState();
                        model.addRow(row);
                    }
                });
    }

    public void populateApprovedTrials() {

    }

    public void populateCompletedTrials() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingClinicalTrials = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        rejectedClinicalTrial = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        completedClinicalTrialTable = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        startTrialBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Manage Clinical Study");

        pendingClinicalTrials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clinical Study", "Disease", "Drug", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pendingClinicalTrials);

        rejectedClinicalTrial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(rejectedClinicalTrial);

        completedClinicalTrialTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(completedClinicalTrialTable);

        editBtn.setText("start trial");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("reject trial");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        startTrialBtn.setText("view results");
        startTrialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTrialBtnActionPerformed(evt);
            }
        });

        backBtn.setText("back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(backBtn))
                            .addComponent(startTrialBtn)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startTrialBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = pendingClinicalTrials.getSelectedRow();
        if (selectedRow >= 0) {
            WorkRequest wr = (WorkRequest) pendingClinicalTrials.getValueAt(selectedRow, 0);
            startClinicalTrial(wr);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row first");
        }
    }//GEN-LAST:event_editBtnActionPerformed

    public void startClinicalTrial(WorkRequest wr) {
        
    
    }
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void startTrialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTrialBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startTrialBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable completedClinicalTrialTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable pendingClinicalTrials;
    private javax.swing.JTable rejectedClinicalTrial;
    private javax.swing.JButton startTrialBtn;
    // End of variables declaration//GEN-END:variables
}
