/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.organization.admin.drug.view;

import java.awt.CardLayout;
import javax.swing.JPanel;
import org.biogen.business.enterprise.model.BusinessUnitType;
import org.biogen.business.enterprise.model.DrugManufacturingBusiness;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.network.model.OperationalRegion;
import org.biogen.organization.model.DrugManufactuer;
import org.biogen.user.model.BusinessUser;

/**
 *
 * @author deveshkandpal
 */
public class DrugOrgAdminMainWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugAdminWorkPanel
     */
    private Ecosystem system;
    private JPanel container;
    private BusinessUser user;
    private OperationalRegion network;
    private DrugManufacturingBusiness enterprise;
    private DrugManufactuer organization;

    public DrugOrgAdminMainWorkPanel(Ecosystem system, JPanel container, BusinessUser user) {
        initComponents();
        this.system = system;
        this.container = container;
        this.user = user;
        populateUserDetails();
    }

    public void populateUserDetails() {
        this.network = this.system.getOpRegionDirectory().getOperationalRegionList()
                .stream().filter(op -> op.getRegionId() == user.getNetworkId())
                .findFirst()
                .get();

        this.enterprise = this.network.getBuDir()
                .getBusinessUnitList()
                .stream()
                .filter(bu -> bu.getUnitType() == BusinessUnitType.DRUG)
                .map(enter -> (DrugManufacturingBusiness) enter)
                .filter(drugBus -> drugBus.getEnterpriseId() == user.getEnterpriseId())
                .findFirst()
                .get();

        System.out.println("user.getOrganizationId():" + user.getOrganizationId());
        System.out.println("user.getOrganizationId():" + this.enterprise);

        this.organization = (DrugManufactuer) this.enterprise
                .getOrganizationList()
                .stream()
                .filter(drugOrg -> drugOrg.getOrgId() == user.getOrganizationId())
                .findFirst()
                .get();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mngInventoryBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mngDrugCreationBtn = new javax.swing.JButton();
        mngDrugSynthesis = new javax.swing.JButton();
        dashboardBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        mngInventoryBtn.setText("Manage Inventory");
        mngInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngInventoryBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Drug Organization Work Area");

        mngDrugCreationBtn.setText("Manage Drug Creation");
        mngDrugCreationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngDrugCreationBtnActionPerformed(evt);
            }
        });

        mngDrugSynthesis.setText("Manage Drug Synthesis");
        mngDrugSynthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngDrugSynthesisActionPerformed(evt);
            }
        });

        dashboardBtn.setText("Analytics Dashboard");
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mngDrugSynthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(mngDrugCreationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mngInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dashboardBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(mngInventoryBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mngDrugCreationBtn)
                .addGap(18, 18, 18)
                .addComponent(mngDrugSynthesis)
                .addGap(18, 18, 18)
                .addComponent(dashboardBtn)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mngInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngInventoryBtnActionPerformed
        // TODO add your handling code here:
        ManageInventoryPanel panel = new ManageInventoryPanel(container, user, system, organization, enterprise, network);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ManageInventoryPanel", panel);
        layout.next(container);
    }//GEN-LAST:event_mngInventoryBtnActionPerformed

    private void mngDrugCreationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngDrugCreationBtnActionPerformed
        // TODO add your handling code here:
        ManageDrugCreationPanel panel = new ManageDrugCreationPanel(container, system, enterprise, organization, user);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ManageDrugCreationPanel", panel);
        layout.next(container);
    }//GEN-LAST:event_mngDrugCreationBtnActionPerformed

    private void mngDrugSynthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngDrugSynthesisActionPerformed
        // TODO add your handling code here:
        ManageDrugSynthesis panel = new ManageDrugSynthesis(organization, container);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ManageDrugSynthesis", panel);
        layout.next(container);

    }//GEN-LAST:event_mngDrugSynthesisActionPerformed

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        DrugOrgAnalyticsDashboard panel = new DrugOrgAnalyticsDashboard(organization, container);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("DrugOrgAnalyticsDashboard", panel);
        layout.next(container);
    }//GEN-LAST:event_dashboardBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngDrugCreationBtn;
    private javax.swing.JButton mngDrugSynthesis;
    private javax.swing.JButton mngInventoryBtn;
    // End of variables declaration//GEN-END:variables
}
