/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.organization.admin.drug.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.biogen.business.chem.model.Compound;
import org.biogen.business.drug.model.Item;
import org.biogen.business.drug.model.ItemOrder;
import org.biogen.business.enterprise.model.DrugManufacturingBusiness;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.organization.model.ChemicalManufacturer;
import org.biogen.organization.model.DrugManufactuer;
import org.biogen.organization.model.DrugManufacturerDirectory;
import org.biogen.organization.work.model.WorkRequest;
import org.biogen.organization.work.model.WorkRequestStatus;
import org.biogen.user.model.BusinessUser;
import org.biogen.user.model.RoleType;
import org.biogen.user.model.UserType;
import org.biogen.work.attachment.model.AttachmentType;
import org.biogen.work.attachment.model.InventoryUpdateAttachment;

/**
 *
 * @author deveshkandpal
 */
public class EditAnticipatedInventoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditAnticipatedInventoryPanel
     */
    private ItemOrder itemOrder;
    private JPanel container;
    private Ecosystem system;
    private Item item;
    private DrugManufactuer organization;
    private DrugManufacturingBusiness enterprise;
    
    public EditAnticipatedInventoryPanel(ItemOrder itemOrder, JPanel container,
            Ecosystem system,
            Item item,
            DrugManufactuer organization,
            DrugManufacturingBusiness enterprise
    ) {
        initComponents();
        this.itemOrder = itemOrder;
        this.container = container;
        this.system = system;
        this.item = item;
        this.organization = organization;
        this.enterprise = enterprise;
        populateForm();
    }
    
    private void populateForm() {
        compoundNameField.setText(item.getCompound().toString());
        quantityField.setText(String.valueOf(itemOrder.getQuantity()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        compoundNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Edit Requested Inventory");

        jLabel2.setText("Compound Name");

        compoundNameField.setEditable(false);
        compoundNameField.setEnabled(false);

        jLabel3.setText("Quantity");

        updateBtn.setText("update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(backBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(compoundNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(quantityField))))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(updateBtn)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(compoundNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(updateBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addGap(62, 62, 62))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        redirectUser();
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int quantity = Integer.valueOf(quantityField.getText());
        if (quantity > 0) {
            handleWorkOrderCreation(quantity);
            redirectUser();
        } else {
            JOptionPane.showMessageDialog(null, "Quantity has to be > 0 ");
            
        }
    }//GEN-LAST:event_updateBtnActionPerformed
    
    public void redirectUser() {
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageInventoryPanel previousPanel = (ManageInventoryPanel) component;
        previousPanel.populateAnticipatedInventory();
        previousPanel.populateCompoundTable();
        previousPanel.populateExistingInventory();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }
    
    public void handleWorkOrderCreation(int quantity) {
        
        DrugManufactuer receiverOrg = (DrugManufactuer)this.itemOrder.getOrganization();
        
        BusinessUser receiver = receiverOrg.getUserList()
                .stream()
                .filter(u -> u.getType() == UserType.BU)
                .map(us -> (BusinessUser) us)
                .filter(use -> use.getRole().getType() == RoleType.ORG_ADMIN)
                .findFirst()
                .get();
        
        WorkRequest request = receiver.getWorkQueue().getWorkRequestList().
                stream().filter(wr -> wr.getWorkRequestId() == itemOrder.getWorkRequestId())
                .findFirst()
                .get();
        InventoryUpdateAttachment iAttach = (InventoryUpdateAttachment) request.getAttachment();
        iAttach.getItemOrder().setQuantity(quantity);
        request.setComments("Please provide " + quantity + " units of " + item.getCompound().getName());
        request.setStartDate(new Date());
        request.setStatus(WorkRequestStatus.UPDATED);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField compoundNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
