/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.organization.admin.drug.view;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.biogen.business.chem.model.Compound;
import org.biogen.business.common.Status;
import org.biogen.business.drug.model.Drug;
import org.biogen.business.enterprise.model.DrugManufacturingBusiness;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.organization.model.DrugManufactuer;
import org.biogen.organization.work.model.WorkRequest;
import org.biogen.organization.work.model.WorkRequestStatus;
import org.biogen.user.model.BusinessUser;
import org.biogen.work.attachment.model.AttachmentType;
import org.biogen.work.attachment.model.NewCompoundApprovalAttachment;
import org.biogen.work.attachment.model.NewDrugApprovalAttachment;

/**
 *
 * @author deveshkandpal
 */
public class ManageDrugCreationPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDrugCreationPanel
     */
    private JPanel container;
    private Ecosystem system;
    private DrugManufacturingBusiness enterprise;
    private DrugManufactuer organization;
    private BusinessUser user;

    public ManageDrugCreationPanel(
            JPanel container,
            Ecosystem system,
            DrugManufacturingBusiness enterprise,
            DrugManufactuer organization,
            BusinessUser user
    ) {
        initComponents();
        this.container = container;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        this.user = user;
        populateNewDrugTable();
        populateApprovedOrDeniedCompoundRequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void populateNewDrugTable() {

        DefaultTableModel model = (DefaultTableModel) newDrugTable.getModel();

        model.setRowCount(0);
        System.out.println("drugs size : " + this.organization.getDrugList().size());
        this.organization.getDrugList().stream()
                .filter(d -> d.getStatus() != Status.APPROVED && d.getStatus() != Status.REJECTED)
                .forEach(dr -> {
                    Object[] row = new Object[4];
                    row[0] = dr;
                    row[1] = dr.getDisease();
                    row[2] = dr.getCreatedOn();
                    row[3] = dr.getStatus().toString();
                    model.addRow(row);
                });

    }

    public void populateApprovedOrDeniedCompoundRequest() {
        DefaultTableModel model = (DefaultTableModel) approvedDrugTable.getModel();

        model.setRowCount(0);
        this.organization.getDrugList().stream()
                .filter(com -> com.getStatus() == Status.APPROVED
                || com.getStatus() == Status.REJECTED)
                .forEach(dr -> {
                    Object[] row = new Object[5];
                    row[0] = dr;
                    row[1] = dr.getDisease();
                    row[2] = dr.getCreatedOn();
                    row[3] = dr.getStatus().toString();
                    if (dr.getStatus() == Status.REJECTED) {
                        WorkRequest request = retrieveWorkRequest(dr, WorkRequestStatus.APPROVED, WorkRequestStatus.DENIED);
                        row[4] = request.getComments();
                    } else {
                        row[4] = "";
                    }
                    model.addRow(row);
                });

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newDrugTable = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        createNewBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        approvedDrugTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Manage Drug Creation");

        newDrugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Targeted Disease", "Created On", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(newDrugTable);

        editBtn.setText("Edit Drug");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Drug");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        createNewBtn.setText("Create New");
        createNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewBtnActionPerformed(evt);
            }
        });

        approvedDrugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Targeted Disease", "Created On", "Status", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(approvedDrugTable);

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn)
                                .addGap(47, 47, 47)
                                .addComponent(createNewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(createNewBtn))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = newDrugTable.getSelectedRow();
        if (selectedRow >= 0) {
            Drug drug = (Drug) newDrugTable.getValueAt(selectedRow, 0);
            EditNewDrugPanel panel = new EditNewDrugPanel(container, system, enterprise, organization, user, drug);
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("EditNewDrugPanel", panel);
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a compound request to be modified");
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = newDrugTable.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete ?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Drug drug = (Drug) newDrugTable.getValueAt(selectedRow, 0);

                this.system.getDrugDirectory().removeDrug(drug);
                this.enterprise.getDrugList().remove(drug);
                this.organization.getDrugList().remove(drug);
                this.populateNewDrugTable();
                updateWorkOrderRequest(drug);
                JOptionPane.showMessageDialog(null, "New Compound Request deleted succesfully");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please Select a compound request to be deleted");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    public void updateWorkOrderRequest(Drug drug) {
        WorkRequest workRequest = retrieveWorkRequest(drug, WorkRequestStatus.NEW, WorkRequestStatus.UPDATED);
        workRequest.setStatus(WorkRequestStatus.CANCELLED);

    }

    public WorkRequest retrieveWorkRequest(Drug drug, WorkRequestStatus s1, WorkRequestStatus s2) {

        WorkRequest request = this.enterprise.getWorkQueue().getWorkRequestList().stream()
                .filter(wr -> wr.getAttachment().getAttachmentType() == AttachmentType.NewDrugApprovalAttachment)
                .filter(fwr -> {
                    NewDrugApprovalAttachment attach
                            = (NewDrugApprovalAttachment) fwr.getAttachment();
                    if (attach.getDrug() == drug && (fwr.getStatus()
                            == s1 || fwr.getStatus() == s2)) {
                        return true;
                    } else {
                        return false;
                    }
                })
                .findFirst()
                .get();
        return request;
    }


    private void createNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewBtnActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) container.getLayout();
        CreateNewDrugPanel panel = new CreateNewDrugPanel(container, system, enterprise, organization, user);
        container.add("CreateNewDrugPanel", panel);
        layout.next(container);
    }//GEN-LAST:event_createNewBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable approvedDrugTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createNewBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable newDrugTable;
    // End of variables declaration//GEN-END:variables
}
