/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.organization.admin.drug.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.biogen.business.enterprise.model.DrugManufacturingBusiness;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.order.model.ChemicalSynthesisOrder;
import org.biogen.organization.model.DrugManufactuer;
import org.biogen.organization.work.model.WorkRequest;
import org.biogen.user.model.BusinessUser;
import org.biogen.user.model.RoleType;
import org.biogen.user.model.UserType;
import org.biogen.work.attachment.model.AttachmentType;
import org.biogen.work.attachment.model.InventoryUpdateAttachment;
import org.biogen.business.drug.model.Item;
import org.biogen.business.drug.model.ItemOrder;
import org.biogen.business.drug.model.ItemStatus;
import org.biogen.network.model.OperationalRegionType;
import org.biogen.organization.admin.chem.view.ManageNewCompoundRequestPanel;
import org.biogen.organization.model.ChemicalManufacturer;
import org.biogen.organization.work.model.WorkRequestStatus;

/**
 *
 * @author deveshkandpal
 */
public class ManageInventoryOrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryOrderPanel
     */
    private JPanel container;
    private Ecosystem system;
    private BusinessUser user;
    private DrugManufactuer organization;
    private DrugManufacturingBusiness enterprise;
    private ChemicalSynthesisOrder chemicalSynthesizedOrder;

    public ManageInventoryOrderPanel(JPanel container,
            Ecosystem system,
            BusinessUser user,
            DrugManufactuer organization,
            DrugManufacturingBusiness enterprise,
            ChemicalSynthesisOrder chemicalSynthesizedOrder) {
        initComponents();
        this.container = container;
        this.system = system;
        this.user = user;
        this.organization = organization;
        this.enterprise = enterprise;
        this.chemicalSynthesizedOrder = chemicalSynthesizedOrder;
        populateForm();
    }

    public void populateForm() {
        compoundNameField.setText(chemicalSynthesizedOrder.toString());
        quantityField.setText(String.valueOf(chemicalSynthesizedOrder.getQuantity()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        compoundNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Compound Name");

        compoundNameField.setEditable(false);
        compoundNameField.setEnabled(false);

        jLabel2.setText("Quantity");

        submitBtn.setText("submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compoundNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(quantityField))))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(compoundNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(submitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        int quantity = Integer.valueOf(quantityField.getText());
        if (quantity > 0 && quantity <= chemicalSynthesizedOrder.getQuantity()) {
            handleWorkOrderCreation(quantity);
            redirectUser();
        } else {
            JOptionPane.showMessageDialog(null, "Quantity has to be > 0 and <"
                    + chemicalSynthesizedOrder.getQuantity());

        }
    }//GEN-LAST:event_submitBtnActionPerformed

    public void redirectUser() {
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageInventoryPanel previousPanel = (ManageInventoryPanel) component;
        previousPanel.populateAnticipatedInventory();
        previousPanel.populateCompoundTable();
        previousPanel.populateExistingInventory();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }

    public void handleWorkOrderCreation(int quantity) {
        ChemicalManufacturer receiverOrg = (ChemicalManufacturer) this.chemicalSynthesizedOrder.getSynthesizingManufacturerId();
//        ChemicalManufacturer receiverOrg = (ChemicalManufacturer) this.system.getOrganizationDirectory().getOrganizationList().stream()
//                .filter(o -> o.getOrgId() == orgId)
//                .findFirst()
//                .get();

        BusinessUser receiver = receiverOrg.getUserList()
                .stream()
                .filter(u -> u.getType() == UserType.BU)
                .map(us -> (BusinessUser) us)
                .filter(use -> use.getRole().getType() == RoleType.ORG_ADMIN)
                .findFirst()
                .get();

        Item item = this.organization.getInventory().addOrReturnItem(chemicalSynthesizedOrder.getCompound());
        ItemOrder itemOrder = item.addItemOrder();
        itemOrder.setItemStatus(ItemStatus.NEW);
        itemOrder.setOrganization((ChemicalManufacturer)chemicalSynthesizedOrder.getSynthesizingManufacturerId());
        itemOrder.setQuantity(Integer.valueOf(quantityField.getText()));

        itemOrder.setRegion(this.system
                .getOpRegionDirectory()
                .getOperationalRegionList()
                .stream()
                .filter(op -> op.getRegionId() == itemOrder
                .getOrganization()
                .getNetworkId())
                .findFirst()
                .get().getType());

        itemOrder.setRequestedOn(new Date());
        WorkRequest request = receiver.getWorkQueue().addWorkRequest();
        request.setComments("Please provide " + quantity + " units of " + chemicalSynthesizedOrder);
        InventoryUpdateAttachment attachment = (InventoryUpdateAttachment) request.addAttachment(AttachmentType.InventoryUpdateAttachment);
        attachment.setCompound(this.chemicalSynthesizedOrder.getCompound());
        attachment.setItemOrder(itemOrder);
        request.setReceiver(receiver);
        request.setSender(user);
        request.setStartDate(new Date());
        request.setStatus(WorkRequestStatus.NEW);
        itemOrder.setWorkRequestId(request.getWorkRequestId());
    }


    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        redirectUser();
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField compoundNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
