/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.organization.admin.chem.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.biogen.business.common.Status;
import org.biogen.business.drug.model.ItemStatus;
import org.biogen.business.enterprise.model.ChemicalManufacturingBusiness;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.enterprise.admin.chem.view.ManageWorkRequestPanel;
import org.biogen.order.model.ChemicalSynthesisOrder;
import org.biogen.organization.model.ChemicalManufacturer;
import org.biogen.organization.work.model.WorkRequest;
import org.biogen.organization.work.model.WorkRequestStatus;
import org.biogen.user.model.BusinessUser;
import org.biogen.work.attachment.model.InventoryUpdateAttachment;
import org.biogen.work.attachment.model.NewCompoundApprovalAttachment;

/**
 *
 * @author deveshkandpal
 */
public class ApproveOrDenyWorkRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApproveOrDenyWorkRequestPanel
     */
    private JPanel container;
    private Ecosystem system;
    private ChemicalManufacturer organization;
    private ChemicalManufacturingBusiness enterprise;
    private BusinessUser user;
    private WorkRequest workRequest;
    private InventoryUpdateAttachment attachment;
    private ChemicalSynthesisOrder chemicalSynthesized;

    public ApproveOrDenyWorkRequestPanel(
            JPanel container,
            Ecosystem system,
            ChemicalManufacturer organization,
            ChemicalManufacturingBusiness enterprise,
            BusinessUser user,
            WorkRequest workRequest,
            InventoryUpdateAttachment attachment
    ) {
        initComponents();

        this.container = container;
        this.system = system;
        this.organization = organization;
        this.enterprise = enterprise;
        this.user = user;
        this.workRequest = workRequest;
        this.attachment = attachment;
        this.chemicalSynthesized = this.organization.getChemicalSynthesisOrderList().stream()
                .filter(cso -> cso.getCompound() == attachment.getCompound())
                .findFirst()
                .get();
        populateForm();
    }

    public void populateForm() {

        requestedByField.setText(workRequest.getSender().toString());
        compoundField.setText(attachment.getCompound().toString());
        requestedQuantityField.setText(String.valueOf(attachment
                .getItemOrder().getQuantity()));

        availableQuantityField.setText(String.valueOf(this.chemicalSynthesized.getQuantity()));
        if (chemicalSynthesized.getQuantity() < attachment.getItemOrder().getQuantity()) {
            synthesizeBtn.setVisible(true);
            synthesizeBtn.setEnabled(true);
            updateBtn.setEnabled(false);
            availableQuantityField.setEnabled(true);
            availableQuantityField.setEditable(true);
        } else {
            synthesizeBtn.setVisible(false);
            synthesizeBtn.setEnabled(false);
            updateBtn.setEnabled(true);
            availableQuantityField.setEnabled(false);
            availableQuantityField.setEditable(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        compoundField = new javax.swing.JTextField();
        requestedQuantityField = new javax.swing.JTextField();
        availableQuantityField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        requestedByField = new javax.swing.JTextField();
        approvalStatusCombo = new javax.swing.JComboBox<>();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        synthesizeBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Vendor Compound Requirement Request");

        jLabel2.setText("Compound");

        jLabel3.setText("Requested Quantity");

        jLabel4.setText("Status");

        jLabel5.setText("Available Quantity");

        compoundField.setEditable(false);
        compoundField.setEnabled(false);

        requestedQuantityField.setEditable(false);
        requestedQuantityField.setEnabled(false);

        jLabel6.setText("Requested By");

        requestedByField.setEditable(false);
        requestedByField.setEnabled(false);
        requestedByField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestedByFieldActionPerformed(evt);
            }
        });

        approvalStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APPROVED", "DENIED" }));

        updateBtn.setText("Update Status");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        synthesizeBtn.setText("synthesize");
        synthesizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                synthesizeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(requestedQuantityField))
                    .addComponent(compoundField)
                    .addComponent(availableQuantityField)
                    .addComponent(requestedByField)
                    .addComponent(approvalStatusCombo, 0, 132, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(synthesizeBtn)
                .addGap(0, 169, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateBtn)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestedByField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(compoundField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(requestedQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(availableQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(synthesizeBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(approvalStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(updateBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addGap(53, 53, 53))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestedByFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestedByFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestedByFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        this.workRequest.setEndDate(new Date());

        if (approvalStatusCombo.getSelectedItem().equals("APPROVED")) {
            this.workRequest.setStatus(WorkRequestStatus.APPROVED);
            this.workRequest.setComments("Request Approved");
            this.chemicalSynthesized.setQuantity(this.chemicalSynthesized.getQuantity() - this.attachment.getItemOrder().getQuantity());
            this.attachment.getItemOrder().setItemStatus(ItemStatus.APPROVED);

        } else {
            this.workRequest.setStatus(WorkRequestStatus.DENIED);
            this.workRequest.setComments("Request Rejected");
            this.attachment.getItemOrder().setItemStatus(ItemStatus.DENIED);
        }

        redirectUser();

    }//GEN-LAST:event_updateBtnActionPerformed

    public void redirectUser() {
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageVendorRequest previousPanel = (ManageVendorRequest) component;
        previousPanel.populateVendorRequestTable();
        previousPanel.populateOtherRequestTable();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        redirectUser();
    }//GEN-LAST:event_backBtnActionPerformed

    private void synthesizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_synthesizeBtnActionPerformed
        // TODO add your handling code here:
        this.organization.createOrUpdateOrder(attachment.getCompound(),
                Integer.valueOf(availableQuantityField.getText()));
        JOptionPane.showMessageDialog(null, "Inventory has been updated");
        populateForm();

    }//GEN-LAST:event_synthesizeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> approvalStatusCombo;
    private javax.swing.JTextField availableQuantityField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField compoundField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField requestedByField;
    private javax.swing.JTextField requestedQuantityField;
    private javax.swing.JButton synthesizeBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
