/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.organization.admin.chem.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.biogen.business.chem.model.Compound;
import org.biogen.business.common.Status;
import org.biogen.business.enterprise.model.BusinessUnitType;
import org.biogen.business.enterprise.model.ChemicalManufacturingBusiness;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.ecosystem.model.Organization;
import org.biogen.organization.model.ChemicalManufacturer;
import org.biogen.organization.work.model.WorkRequest;
import org.biogen.organization.work.model.WorkRequestStatus;
import org.biogen.user.model.BusinessUser;
import org.biogen.user.model.RoleType;
import org.biogen.user.model.UserType;
import org.biogen.work.attachment.model.AttachmentType;
import org.biogen.work.attachment.model.NewCompoundApprovalAttachment;

/**
 *
 * @author deveshkandpal
 */
public class CreateNewCompoundPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewCompoundPanel
     */
    private Ecosystem system;
    private JPanel container;
    private BusinessUser user;
    private ChemicalManufacturingBusiness enterprise;
    private ChemicalManufacturer organization;

    public CreateNewCompoundPanel(Ecosystem system, JPanel container,
            BusinessUser user,
            ChemicalManufacturingBusiness enterprise,
            ChemicalManufacturer organization) {
        initComponents();
        this.system = system;
        this.container = container;
        this.user = user;
        this.enterprise = enterprise;
        this.organization = organization;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        formulaField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionField = new javax.swing.JTextArea();
        subtmitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Create New Compound");

        jLabel2.setText("Name");

        jLabel3.setText("Formula");

        jLabel4.setText("Description");

        descriptionField.setColumns(20);
        descriptionField.setRows(5);
        jScrollPane1.setViewportView(descriptionField);

        subtmitBtn.setText("submit");
        subtmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtmitBtnActionPerformed(evt);
            }
        });

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subtmitBtn)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(formulaField)
                                        .addComponent(nameField)))))
                        .addContainerGap(126, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(formulaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4)))))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtmitBtn)
                    .addComponent(backBtn))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subtmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtmitBtnActionPerformed
        // TODO add your handling code here:

        if (!descriptionField.getText().trim().equalsIgnoreCase("")
                && !nameField.getText().trim().equalsIgnoreCase("")
                && !formulaField.getText().trim().equalsIgnoreCase("")) {

            Compound compound = this.enterprise.getCompoundDirectory().addNewCompound();
            organization.getCompoundList().add(compound);

            compound.setDescription(descriptionField.getText());
            compound.setName(nameField.getText());
            compound.setFormula(formulaField.getText());
            compound.setCreatedOn(new Date());
            compound.setManufacturerId(organization.getOrgId());
            compound.setStatus(Status.NEW);

            // send request to enterprise head;
            BusinessUser enterpriseHead = this.enterprise.getUserList().stream()
                    .filter(u -> u.getType() == UserType.BU)
                    .map(fu -> (BusinessUser) fu)
                    .filter(obj -> obj.getRole().getType() == RoleType.ENTERPRISE_ADMIN)
                    .findFirst()
                    .get();

            System.out.println("Enterprise Head " + enterpriseHead.getUserId());
            System.out.println("Org Head " + user.getOrganizationId());
            WorkRequest request = prepareWorkRequest(compound, enterpriseHead);

            descriptionField.setText("");
            formulaField.setText("");
            nameField.setText("");
            // show results of messages received only in which you are either the sender or receiver

        } else {
            JOptionPane.showMessageDialog(null, "Kindly enter name, formula and description");
        }
    }//GEN-LAST:event_subtmitBtnActionPerformed

    public WorkRequest prepareWorkRequest(Compound compound, BusinessUser enterpriseHead) {

        WorkRequest request = this.enterprise.getWorkQueue().addWorkRequest();
        request.setSender(user);
        request.setComments("Seeking Approval for new compound");
        request.setReceiver(enterpriseHead);
        request.setStartDate(new Date());
        NewCompoundApprovalAttachment attachment
                = (NewCompoundApprovalAttachment) request
                        .addAttachment(AttachmentType.NewCompoundApprovalAttachment);

        attachment.setCompound(compound);
        attachment.setWorkRequestId(request.getWorkRequestId());
        request.setAttachment(attachment);
        request.setStatus(WorkRequestStatus.NEW);
        return request;

    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageNewCompoundRequestPanel previousPanel = (ManageNewCompoundRequestPanel) component;
        previousPanel.populateNewCompoundRequest();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea descriptionField;
    private javax.swing.JTextField formulaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton subtmitBtn;
    // End of variables declaration//GEN-END:variables
}
