/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.organization.admin.chem.view;

import java.awt.CardLayout;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.biogen.business.chem.model.Compound;
import org.biogen.business.common.Status;

import org.biogen.business.enterprise.model.ChemicalManufacturingBusiness;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.organization.model.ChemicalManufacturer;
import org.biogen.organization.work.model.WorkRequest;
import org.biogen.organization.work.model.WorkRequestStatus;
import org.biogen.user.model.BusinessUser;
import org.biogen.work.attachment.model.AttachmentType;
import org.biogen.work.attachment.model.NewCompoundApprovalAttachment;

/**
 *
 * @author deveshkandpal
 */
public class ManageNewCompoundRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChemAdminWorkPanel
     */
    private Ecosystem system;
    private JPanel container;
    private BusinessUser user;
    private ChemicalManufacturingBusiness enterprise;
    private ChemicalManufacturer organization;

    public ManageNewCompoundRequestPanel(Ecosystem system, JPanel container, BusinessUser user,
            ChemicalManufacturingBusiness enterprise,
            ChemicalManufacturer organization) {
        initComponents();
        this.system = system;
        this.container = container;
        this.user = user;
        this.enterprise = enterprise;
        this.organization = organization;
        populateNewCompoundRequest();
        populateApprovedOrDeniedCompoundRequest();
    }

    public void populateNewCompoundRequest() {
        DefaultTableModel model = (DefaultTableModel) newCompoundTable.getModel();

        model.setRowCount(0);
        this.organization.getCompoundList().stream()
                .filter(com -> com.getStatus() != Status.APPROVED && com.getStatus() != Status.REJECTED)
                .forEach(c -> {
                    Object[] row = new Object[4];
                    row[0] = c;
                    row[1] = c.getFormula();
                    row[2] = c.getCreatedOn();
                    row[3] = c.getStatus().toString();
                    model.addRow(row);
                });

    }

    public void populateApprovedOrDeniedCompoundRequest() {
        DefaultTableModel model = (DefaultTableModel) approvedCompoundTable.getModel();

        model.setRowCount(0);
        this.organization.getCompoundList().stream()
                .filter(com -> com.getStatus() == Status.APPROVED
                || com.getStatus() == Status.REJECTED)
                .forEach(c -> {
                    Object[] row = new Object[5];
                    row[0] = c;
                    row[1] = c.getFormula();
                    row[2] = c.getCreatedOn();
                    row[3] = c.getStatus().toString();
                    if (c.getStatus() == Status.REJECTED) {
                        WorkRequest request = retrieveWorkRequest(c);
                        row[4] = request.getComments();
                    } else {
                        row[4] = "";
                    }
                    model.addRow(row);
                });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newCompoundTable = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        createNewBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        approvedCompoundTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Manage New Compound Request");

        newCompoundTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compound Name", "Formula", "Created On", "Status"
            }
        ));
        jScrollPane1.setViewportView(newCompoundTable);

        editBtn.setText("Edit Compound");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Compound");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        createNewBtn.setText("Create New");
        createNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewBtnActionPerformed(evt);
            }
        });

        approvedCompoundTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compound Name", "Formula", "Created On", "Status", "Comments"
            }
        ));
        jScrollPane2.setViewportView(approvedCompoundTable);

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(editBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(deleteBtn)
                                    .addGap(20, 20, 20)
                                    .addComponent(createNewBtn))))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn)
                    .addComponent(deleteBtn)
                    .addComponent(createNewBtn))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = newCompoundTable.getSelectedRow();
        if (selectedRow >= 0) {
            Compound compound = (Compound) newCompoundTable.getValueAt(selectedRow, 0);
            EditNewCompoundPanel panel = new EditNewCompoundPanel(system,
                    container, user, enterprise, organization, compound);
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("EditNewCompoundPanel", panel);
            layout.next(container);
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a compound request to be modified");
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = newCompoundTable.getSelectedRow();
        if (selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete ?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                Compound compound = (Compound) newCompoundTable.getValueAt(selectedRow, 0);
                enterprise.getCompoundDirectory().removeCompound(compound);
                organization.getCompoundList().remove(compound);
                this.populateNewCompoundRequest();
                updateWorkOrderRequest(compound);
                JOptionPane.showMessageDialog(null, "New Compound Request deleted succesfully");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please Select a compound request to be deleted");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    // cancel work order
    public void updateWorkOrderRequest(Compound compound) {
        WorkRequest workRequest = retrieveWorkRequest(compound);
        workRequest.setStatus(WorkRequestStatus.CANCELLED);

    }

    public WorkRequest retrieveWorkRequest(Compound compound) {

        WorkRequest request = this.enterprise.getWorkQueue().getWorkRequestList().stream()
                .filter(wr -> wr.getAttachment().getAttachmentType() == AttachmentType.NewCompoundApprovalAttachment)
                .filter(fwr -> {
                    NewCompoundApprovalAttachment attach
                            = (NewCompoundApprovalAttachment) fwr.getAttachment();
                    if (attach.getCompound() == compound && (fwr.getStatus()
                            == WorkRequestStatus.NEW || fwr.getStatus() == WorkRequestStatus.UPDATED)) {
                        return true;
                    } else {
                        return false;
                    }
                })
                .findFirst()
                .get();
        return request;
    }
    
    private void createNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewBtnActionPerformed
        // TODO add your handling code here:
        CreateNewCompoundPanel panel = new CreateNewCompoundPanel(system,
                container, user, enterprise, organization);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("CreateNewCompoundPanel", panel);
        layout.next(container);
    }//GEN-LAST:event_createNewBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable approvedCompoundTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createNewBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable newCompoundTable;
    // End of variables declaration//GEN-END:variables
}
