/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.ecosystem.admin.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.biogen.business.drug.model.Drug;
import org.biogen.business.medicare.model.ClinicalState;
import org.biogen.business.medicare.model.ClinicalStudy;
import org.biogen.business.medicare.model.Disease;
import org.biogen.business.medicare.model.TrialType;
import org.biogen.ecosystem.model.Ecosystem;

/**
 *
 * @author deveshkandpal
 */
public class EditClinicalStudyPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditClinicalStudyPanel
     */
    private Ecosystem system;
    private JPanel container;
    private ClinicalStudy study;

    public EditClinicalStudyPanel(
            Ecosystem system,
            JPanel container,
            ClinicalStudy study
    ) {
        initComponents();
        this.system = system;
        this.container = container;
        this.study = study;
        populateDetails();

    }

    public void populateDetails() {
        System.out.println("study.getStudyName():" + study.getStudyName());
        System.out.println("study.getStudyName():" + study.getClinicalStudyId());
        System.out.println("study.getStudyName():" + study.getDrug());
        System.out.println("study.getDisease():" + study.getDrug().getDisease());
        System.out.println("study.getStudyName():" + study.getState());
        studyNameField.setText(study.getStudyName());
        trialTypeField.setSelectedItem(study.getTrialType());
        populateDiseaseDropDown();
    }

    public void populateDiseaseDropDown() {

        diseaseNameField.removeAllItems();
        this.system.getDiseaseStudyDirectory().getDiseaseList()
                .stream()
                .forEach(d -> {
                    // if (d != study.getDrug().getDisease()) {
                    System.out.println("if study.getDrug().getDisease()" + d);
                    diseaseNameField.addItem(d);
                    //   } else {
                    //      System.out.println("else study.getDrug().getDisease()" + d);
                    //   }
                });

        diseaseNameField.setSelectedItem(study.getDrug().getDisease());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        studyNameField = new javax.swing.JTextField();
        diseaseNameField = new javax.swing.JComboBox();
        drugNameField = new javax.swing.JComboBox();
        trialTypeField = new javax.swing.JComboBox<>();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Edit Clinical Study");

        jLabel2.setText("Study Name");

        jLabel3.setText("Disease Name");

        jLabel4.setText("Drug Name");

        jLabel5.setText("Trial Type");

        diseaseNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseaseNameFieldActionPerformed(evt);
            }
        });

        drugNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugNameFieldActionPerformed(evt);
            }
        });

        trialTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUCKET", "UMBERELLA" }));

        submitBtn.setText("update");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(studyNameField)
                                    .addComponent(diseaseNameField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(drugNameField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(trialTypeField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addGap(193, 193, 193)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(diseaseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(drugNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(trialTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(submitBtn)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void diseaseNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseaseNameFieldActionPerformed
        // TODO add your handling code here:
        Disease disease = (Disease) diseaseNameField.getSelectedItem();
        drugNameField.removeAllItems();
        this.system.getDrugDirectory().getDrugList()
                .stream()
                .filter(d -> d.getDisease() == disease)
                .collect(Collectors.toList())
                .stream()
                .forEach(drug -> {
                    drugNameField.addItem(drug);
                });
    }//GEN-LAST:event_diseaseNameFieldActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String studyName = studyNameField.getText();
        Disease disease = (Disease) diseaseNameField.getSelectedItem();
        Drug drug = (Drug) drugNameField.getSelectedItem();
        TrialType trialType = ((String) trialTypeField.getSelectedItem()).
                equals("BUCKET") ? TrialType.BUCKET : TrialType.UMBERELLA;

        if (studyName != null && disease != null && drug != null) {
            this.study.setStudyName(studyName);
            this.study.setDrug(drug);
            this.study.setState(ClinicalState.NEW);
            this.study.setTrialType(trialType);
            redirectUser();
        } else {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        redirectUser();
    }//GEN-LAST:event_backBtnActionPerformed

    public void redirectUser() {

        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageClinicalTrialPanel previousPanel = (ManageClinicalTrialPanel) component;
        // call previous panel methods
        previousPanel.populateExistingClinicalStudy();
        previousPanel.populateNewClinicalStudy();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }

    private void drugNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugNameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox diseaseNameField;
    private javax.swing.JComboBox drugNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField studyNameField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JComboBox<String> trialTypeField;
    // End of variables declaration//GEN-END:variables
}
