/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.enterprise.admin.drug.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.biogen.business.chem.model.Compound;
import org.biogen.business.common.Status;
import org.biogen.business.drug.model.Drug;
import org.biogen.organization.work.model.WorkRequest;
import org.biogen.organization.work.model.WorkRequestStatus;
import org.biogen.work.attachment.model.NewCompoundApprovalAttachment;
import org.biogen.work.attachment.model.NewDrugApprovalAttachment;

/**
 *
 * @author deveshkandpal
 */
public class ApproveOrDeclineNewDrugWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form ApproveOrDeclineNewDrugWorkRequest
     */
    private JPanel container;
    private WorkRequest workRequest;

    public ApproveOrDeclineNewDrugWorkRequest(JPanel container, WorkRequest workRequest) {
        initComponents();
        this.workRequest = workRequest;
        this.container = container;
        populateForm();
    }

    public void populateForm() {
        NewDrugApprovalAttachment attachment = (NewDrugApprovalAttachment) workRequest.getAttachment();
        Drug drug = attachment.getDrug();
        drugNameField.setText(drug.getName());
        targetedDiseaseField.setText(drug.getDisease().toString());
        populateTargetedGene(drug);
        strengthField.setText(String.valueOf(drug.getStrength()));
        routeField.setText(drug.getRouteType().toString());
        populateDrugComposition(drug);

    }

    public void populateTargetedGene(Drug drug) {
        DefaultTableModel model = (DefaultTableModel) targetedGeneTable.getModel();
        model.setRowCount(0);
        drug.getTargetedGenes()
                .stream()
                .forEach(a -> {
                    Object[] arr = new Object[1];
                    arr[0] = a;
                    model.addRow(arr);
                });
    }

    public void populateDrugComposition(Drug drug) {
        DefaultTableModel model = (DefaultTableModel) drugCompositionTable.getModel();
        model.setRowCount(0);
        drug.getDrugCompositionCatalog().getDrugCompositionList()
                .stream()
                .forEach(dc -> {
                    Object[] arr = new Object[2];
                    Compound c = dc.getCompound();
                    int quantity = dc.getUnit();
                    arr[0] = c;
                    arr[1] = quantity;
                    model.addRow(arr);
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        drugNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        targetedGeneTable = new javax.swing.JTable();
        routeField = new javax.swing.JTextField();
        targetedDiseaseField = new javax.swing.JTextField();
        strengthField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugCompositionTable = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Drug Name");

        drugNameField.setEditable(false);
        drugNameField.setEnabled(false);

        jLabel3.setText("Targeted Disease");

        jLabel4.setText("Targeted Gene");

        jLabel5.setText("Strength");

        jLabel6.setText("Route");

        targetedGeneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Targeted Genes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        targetedGeneTable.setEnabled(false);
        jScrollPane1.setViewportView(targetedGeneTable);

        routeField.setEditable(false);
        routeField.setEnabled(false);
        routeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeFieldActionPerformed(evt);
            }
        });

        targetedDiseaseField.setEditable(false);
        targetedDiseaseField.setEnabled(false);
        targetedDiseaseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetedDiseaseFieldActionPerformed(evt);
            }
        });

        strengthField.setEditable(false);
        strengthField.setEnabled(false);
        strengthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strengthFieldActionPerformed(evt);
            }
        });

        drugCompositionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compound", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugCompositionTable.setEnabled(false);
        jScrollPane2.setViewportView(drugCompositionTable);
        if (drugCompositionTable.getColumnModel().getColumnCount() > 0) {
            drugCompositionTable.getColumnModel().getColumn(1).setHeaderValue("Quantity");
        }

        updateBtn.setText("update request");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        backBtn.setText("back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Approve or Deny Drug Request");

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APPROVE", "DECLINE" }));

        jLabel7.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(routeField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(strengthField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(targetedDiseaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drugNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backBtn)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(130, 130, 130)
                                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drugNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(targetedDiseaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(strengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(routeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(updateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void targetedDiseaseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetedDiseaseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetedDiseaseFieldActionPerformed

    private void strengthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strengthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strengthFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        this.workRequest.setEndDate(new Date());
        NewDrugApprovalAttachment attachment = (NewDrugApprovalAttachment) this.workRequest.getAttachment();

        if (statusComboBox.getSelectedItem().equals("APPROVE")) {
            this.workRequest.setStatus(WorkRequestStatus.APPROVED);
            this.workRequest.setComments("Request Approved");
            attachment.getDrug().setStatus(Status.APPROVED);

        } else {
            this.workRequest.setStatus(WorkRequestStatus.DENIED);
            this.workRequest.setComments("Request Rejected");
            attachment.getDrug().setStatus(Status.REJECTED);
        }
        redirectUser();
    }//GEN-LAST:event_updateBtnActionPerformed

    
    public void redirectUser() {
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDrugWorkRequestPanel previousPanel = (ManageDrugWorkRequestPanel) component;
        previousPanel.populateNewOrUpdatedWorkRequestTable();
        previousPanel.populateOtherWorkRequestTable();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }
    
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        redirectUser();
    }//GEN-LAST:event_backBtnActionPerformed

    private void routeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable drugCompositionTable;
    private javax.swing.JTextField drugNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField routeField;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField strengthField;
    private javax.swing.JTextField targetedDiseaseField;
    private javax.swing.JTable targetedGeneTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
