/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biogen.enterprise.admin.drug.view;

import java.awt.CardLayout;
import javax.swing.JPanel;
import org.biogen.business.enterprise.model.BusinessUnitType;
import org.biogen.business.enterprise.model.ChemicalManufacturingBusiness;
import org.biogen.business.enterprise.model.DrugManufacturingBusiness;
import org.biogen.ecosystem.model.Ecosystem;
import org.biogen.user.model.BusinessUser;

/**
 *
 * @author deveshkandpal
 */
public class DrugEnterpriseAdminWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugEnterpriseAdminWorkPanel
     */
    private Ecosystem system;
    private JPanel container;
    private BusinessUser user;
    private DrugManufacturingBusiness enterprise;

    public DrugEnterpriseAdminWorkPanel(Ecosystem system,
            JPanel container, BusinessUser user
    ) {
        initComponents();
        this.system = system;
        this.container = container;
        this.user = user;
        populateUserDetails();
    }

    public void populateUserDetails() {

        this.enterprise = system.getOpRegionDirectory().getOperationalRegionList()
                .stream().filter(op -> op.getRegionId() == user.getNetworkId())
                .findFirst()
                .get()
                .getBuDir()
                .getBusinessUnitList()
                .stream()
                .filter(bu -> bu.getUnitType() == BusinessUnitType.DRUG)
                .map(unit -> (DrugManufacturingBusiness) unit)
                .filter(drugBusiness -> drugBusiness.getEnterpriseId() == user.getEnterpriseId())
                .findFirst()
                .get();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mngWorkRequestBtn = new javax.swing.JButton();
        analyticDashboardBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Drug Enterprise Work Area");

        mngWorkRequestBtn.setText("Manage Work Request");
        mngWorkRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngWorkRequestBtnActionPerformed(evt);
            }
        });

        analyticDashboardBtn.setText("Analytic Dashboard");
        analyticDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyticDashboardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mngWorkRequestBtn)
                    .addComponent(jLabel1)
                    .addComponent(analyticDashboardBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(mngWorkRequestBtn)
                .addGap(43, 43, 43)
                .addComponent(analyticDashboardBtn)
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mngWorkRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngWorkRequestBtnActionPerformed
        // TODO add your handling code here:
        ManageDrugWorkRequestPanel panel = new ManageDrugWorkRequestPanel(system, user, enterprise, container);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ManageDrugWorkRequestPanel", panel);
        layout.next(container);
    }//GEN-LAST:event_mngWorkRequestBtnActionPerformed

    private void analyticDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyticDashboardBtnActionPerformed
        // TODO add your handling code here:
        DrugEnterpriseAnalytics panel = new DrugEnterpriseAnalytics(enterprise, container);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("DrugEnterpriseAnalytics", panel);
        layout.next(container);
    }//GEN-LAST:event_analyticDashboardBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyticDashboardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngWorkRequestBtn;
    // End of variables declaration//GEN-END:variables
}
